# Site settings
title: Poker Companion App
email: adenyangos@gmail.com
github: https://github.com/Adenyangos
linkedin: https://www.linkedin.com/in/adam-denyangos/
description: Poker Companion App Project Webstie
lang: en-US

# baseurl: "/jekyll-doc-theme" # the subpath of your site, e.g. /blog/
baseurl: "Online_Poker_Companion"
# url: https://aksakalli.github.io/jekyll-doc-theme # the base hostname & protocol for your site
url: ""
# git_address: https://github.com/aksakalli/jekyll-doc-theme
# git_edit_address: https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages
github-project-address: https://github.com/Adenyangos/Online_Poker_Companion
youtube-demo-address: https://youtu.be/7ISlwu3q6S4

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: sandstone # cerulean cosmo custom cyborg darkly flatly journal lumen paper readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
