//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Companion
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardAction
    {
        public long Id { get; set; }
        public long HandId { get; set; }
        public short BoardCard { get; set; }
        public int HandActionNumber { get; set; }
    
        public virtual Hand Hand { get; set; }
    }
}
