//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Companion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bol_Model_DBEntities : DbContext
    {
        public Bol_Model_DBEntities()
            : base("name=Bol_Model_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoardAction> BoardActions { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Hand> Hands { get; set; }
        public virtual DbSet<HandPlayer> HandPlayers { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerAction> PlayerActions { get; set; }
    }
}
