//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Companion
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HandPlayer()
        {
            this.PlayerActions = new HashSet<PlayerAction>();
        }
    
        public long Id { get; set; }
        public long HandId { get; set; }
        public int PlayerId { get; set; }
        public int ChipCountStart { get; set; }
        public int Blind { get; set; }
        public short HoldCard1 { get; set; }
        public short HoldCard2 { get; set; }
    
        public virtual Hand Hand { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAction> PlayerActions { get; set; }
    }
}
