//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Companion
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerAction
    {
        public long Id { get; set; }
        public long HandPlayerId { get; set; }
        public int ChipCountChange { get; set; }
        public int HandActionNumber { get; set; }
    
        public virtual HandPlayer HandPlayer { get; set; }
    }
}
